/**
 * Domain Service - Banner Management
 * Orchestrates banner operations using domain entities
 */

const { Banner } = require('../entities');
const { EntityIds } = require('../valueObjects');
const { AggregateNotFoundError, InvalidBannerError } = require('../errors');

class BannerDomainService {
  constructor(bannerRepository) {
    this.bannerRepository = bannerRepository; // Interface: repository
  }

  /**
   * Create a new banner
   * Command: CreateBanner
   */
  async createBanner(command) {
    try {
      const banner = new Banner(
        null, // ID will be generated by repository
        command.name,
        command.imageUrl
      );

      const created = await this.bannerRepository.save(banner);
      return created;
    } catch (error) {
      if (error.message.includes('Banner')) {
        throw new InvalidBannerError(error.message);
      }
      throw error;
    }
  }

  /**
   * Get banner by ID
   * Query: GetBannerById
   */
  async getBannerById(bannerId) {
    const id = EntityIds.bannerId(bannerId);
    const banner = await this.bannerRepository.findById(id);
    
    if (!banner) {
      throw new AggregateNotFoundError('Banner', id.value);
    }

    return banner;
  }

  /**
   * Get all active banners with current active deals/events
   * Query: GetActiveBanners
   */
  async getActiveBanners(now = new Date()) {
    const banners = await this.bannerRepository.findAll();
    return banners.filter(b => b.isActive && this.hasActiveContent(b, now));
  }

  /**
   * Get all banners
   * Query: GetAllBanners
   */
  async getAllBanners() {
    return this.bannerRepository.findAll();
  }

  /**
   * Update banner details
   * Command: UpdateBanner
   */
  async updateBanner(bannerId, command) {
    const id = EntityIds.bannerId(bannerId);
    const banner = await this.bannerRepository.findById(id);
    
    if (!banner) {
      throw new AggregateNotFoundError('Banner', id.value);
    }

    try {
      banner.updateDetails(command.name, command.imageUrl);
      return this.bannerRepository.save(banner);
    } catch (error) {
      throw new InvalidBannerError(error.message);
    }
  }

  /**
   * Activate a banner
   * Command: ActivateBanner
   */
  async activateBanner(bannerId) {
    const id = EntityIds.bannerId(bannerId);
    const banner = await this.bannerRepository.findById(id);
    
    if (!banner) {
      throw new AggregateNotFoundError('Banner', id.value);
    }

    banner.activate();
    return this.bannerRepository.save(banner);
  }

  /**
   * Deactivate a banner
   * Command: DeactivateBanner
   */
  async deactivateBanner(bannerId) {
    const id = EntityIds.bannerId(bannerId);
    const banner = await this.bannerRepository.findById(id);
    
    if (!banner) {
      throw new AggregateNotFoundError('Banner', id.value);
    }

    banner.deactivate();
    return this.bannerRepository.save(banner);
  }

  /**
   * Delete a banner
   * Command: DeleteBanner
   */
  async deleteBanner(bannerId) {
    const id = EntityIds.bannerId(bannerId);
    const banner = await this.bannerRepository.findById(id);
    
    if (!banner) {
      throw new AggregateNotFoundError('Banner', id.value);
    }

    return this.bannerRepository.delete(id);
  }

  /**
   * Helper: Check if banner has active content
   */
  hasActiveContent(banner, now) {
    // In a real scenario, this would check related deals/events
    // For now, just check if banner itself is active
    return banner.isActive;
  }
}

module.exports = BannerDomainService;
