/**
 * Domain Service - Location Management
 * Manages Location aggregate and its child aggregates (hours, menu items)
 */

const { Location } = require('../entities/location');
const { EntityIds } = require('../valueObjects');
const { AggregateNotFoundError, InvalidLocationError } = require('../errors');

class LocationDomainService {
  constructor(locationRepository) {
    this.locationRepository = locationRepository;
  }

  async createLocation(command) {
    try {
      const location = new Location(
        null, // ID generated by repository
        command.name,
        command.address,
        command.latitude,
        command.longitude
      );

      return this.locationRepository.save(location);
    } catch (error) {
      if (error.message.includes('Location')) {
        throw new InvalidLocationError(error.message);
      }
      throw error;
    }
  }

  async getLocationById(locationId) {
    const id = EntityIds.locationId(locationId);
    const location = await this.locationRepository.findById(id);
    
    if (!location) {
      throw new AggregateNotFoundError('Location', id.value);
    }
    return location;
  }

  async getOpenLocations(now = new Date()) {
    const locations = await this.locationRepository.findAll();
    return locations.filter(l => l.isOpenAt(now));
  }

  async getAllLocations() {
    return this.locationRepository.findAll();
  }

  async getLocationsNear(latitude, longitude, radiusKm = 5) {
    const allLocations = await this.locationRepository.findAll();
    return allLocations.filter(l => {
      const distance = this.calculateDistance(
        latitude, longitude,
        l.latitude, l.longitude
      );
      return distance <= radiusKm;
    });
  }

  async updateLocation(locationId, command) {
    const id = EntityIds.locationId(locationId);
    const location = await this.locationRepository.findById(id);
    
    if (!location) {
      throw new AggregateNotFoundError('Location', id.value);
    }

    try {
      location.updateBasicInfo(
        command.name,
        command.address,
        command.latitude,
        command.longitude
      );
      return this.locationRepository.save(location);
    } catch (error) {
      throw new InvalidLocationError(error.message);
    }
  }

  async recordLocationView(locationId) {
    const id = EntityIds.locationId(locationId);
    const location = await this.locationRepository.findById(id);
    
    if (!location) {
      throw new AggregateNotFoundError('Location', id.value);
    }

    location.recordView();
    return this.locationRepository.save(location);
  }

  async deleteLocation(locationId) {
    const id = EntityIds.locationId(locationId);
    const location = await this.locationRepository.findById(id);
    
    if (!location) {
      throw new AggregateNotFoundError('Location', id.value);
    }

    return this.locationRepository.delete(id);
  }

  /**
   * Haversine formula for distance calculation
   */
  calculateDistance(lat1, lon1, lat2, lon2) {
    const R = 6371; // Earth's radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = 
      Math.sin(dLat/2) * Math.sin(dLat/2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  }
}

module.exports = LocationDomainService;
