/**
 * Domain Service - User Management
 */

const { User } = require('../entities/location');
const { EntityIds } = require('../valueObjects');
const { AggregateNotFoundError, InvalidUserError, BusinessRuleViolationError } = require('../errors');

class UserDomainService {
  constructor(userRepository) {
    this.userRepository = userRepository;
  }

  async createUser(command) {
    try {
      const user = new User(
        null, // ID generated by repository
        EntityIds.auth0Id(command.auth0Id),
        command.username,
        command.email
      );

      return this.userRepository.save(user);
    } catch (error) {
      if (error.message.includes('User')) {
        throw new InvalidUserError(error.message);
      }
      throw error;
    }
  }

  async getUserById(userId) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }
    return user;
  }

  async getUserByAuth0Id(auth0Id) {
    const id = EntityIds.auth0Id(auth0Id);
    return this.userRepository.findByAuth0Id(id);
  }

  async updateUserProfile(userId, command) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }

    try {
      user.updateProfile(
        command.username,
        command.email,
        command.bio
      );
      return this.userRepository.save(user);
    } catch (error) {
      throw new InvalidUserError(error.message);
    }
  }

  async updateUserSettings(userId, command) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }

    try {
      user.updateSettings(command);
      return this.userRepository.save(user);
    } catch (error) {
      throw new BusinessRuleViolationError(error.message);
    }
  }

  /**
   * Enable ghost mode for a user
   * Command: EnableGhostMode
   */
  async enableGhostMode(userId, durationMinutes) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }

    if (durationMinutes < 5 || durationMinutes > 1440) {
      throw new BusinessRuleViolationError('Ghost mode duration must be between 5 and 1440 minutes');
    }

    user.enableGhostMode(durationMinutes);
    return this.userRepository.save(user);
  }

  /**
   * Disable ghost mode for a user
   * Command: DisableGhostMode
   */
  async disableGhostMode(userId) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }

    user.disableGhostMode();
    return this.userRepository.save(user);
  }

  /**
   * Update location sharing preference
   * Command: UpdateLocationSharingMode
   */
  async updateLocationSharingMode(userId, mode) {
    const id = EntityIds.userId(userId);
    const user = await this.userRepository.findById(id);
    
    if (!user) {
      throw new AggregateNotFoundError('User', id.value);
    }

    try {
      user.toggleLocationShare(mode);
      return this.userRepository.save(user);
    } catch (error) {
      throw new BusinessRuleViolationError(error.message);
    }
  }

  /**
   * Add favorite location
   * Command: AddFavoriteLocation
   */
  async addFavoriteLocation(userId, locationId) {
    const userId_id = EntityIds.userId(userId);
    const locationId_id = EntityIds.locationId(locationId);
    
    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    user.addFavoriteLocation(locationId_id);
    return this.userRepository.save(user);
  }

  /**
   * Remove favorite location
   * Command: RemoveFavoriteLocation
   */
  async removeFavoriteLocation(userId, locationId) {
    const userId_id = EntityIds.userId(userId);
    const locationId_id = EntityIds.locationId(locationId);
    
    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    user.removeFavoriteLocation(locationId_id);
    return this.userRepository.save(user);
  }

  /**
   * Send friend request
   * Command: SendFriendRequest
   */
  async sendFriendRequest(userId, targetUserId) {
    const userId_id = EntityIds.userId(userId);
    const targetUserId_id = EntityIds.userId(targetUserId);
    
    if (userId === targetUserId) {
      throw new BusinessRuleViolationError('Cannot send friend request to yourself');
    }

    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    if (user.isFriendWith(targetUserId_id)) {
      throw new BusinessRuleViolationError('Already friends with this user');
    }

    const targetUser = await this.userRepository.findById(targetUserId_id);
    if (!targetUser) {
      throw new AggregateNotFoundError('User', targetUserId_id.value);
    }

    if (targetUser.hasPendingRequestFrom(userId_id)) {
      throw new BusinessRuleViolationError('Friend request already pending');
    }

    targetUser.addPendingFriendRequest(userId_id);
    return this.userRepository.save(targetUser);
  }

  /**
   * Accept friend request
   * Command: AcceptFriendRequest
   */
  async acceptFriendRequest(userId, requesterUserId) {
    const userId_id = EntityIds.userId(userId);
    const requesterUserId_id = EntityIds.userId(requesterUserId);
    
    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    if (!user.hasPendingRequestFrom(requesterUserId_id)) {
      throw new BusinessRuleViolationError('No pending friend request from this user');
    }

    const requester = await this.userRepository.findById(requesterUserId_id);
    if (!requester) {
      throw new AggregateNotFoundError('User', requesterUserId_id.value);
    }

    // Add friendship to both users
    user.removePendingFriendRequest(requesterUserId_id);
    user.addFriend(requesterUserId_id);
    requester.addFriend(userId_id);

    await this.userRepository.save(user);
    return this.userRepository.save(requester);
  }

  /**
   * Decline friend request
   * Command: DeclineFriendRequest
   */
  async declineFriendRequest(userId, requesterUserId) {
    const userId_id = EntityIds.userId(userId);
    const requesterUserId_id = EntityIds.userId(requesterUserId);
    
    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    if (!user.hasPendingRequestFrom(requesterUserId_id)) {
      throw new BusinessRuleViolationError('No pending friend request from this user');
    }

    user.removePendingFriendRequest(requesterUserId_id);
    return this.userRepository.save(user);
  }

  /**
   * Remove friend
   * Command: RemoveFriend
   */
  async removeFriend(userId, friendUserId) {
    const userId_id = EntityIds.userId(userId);
    const friendUserId_id = EntityIds.userId(friendUserId);
    
    const user = await this.userRepository.findById(userId_id);
    if (!user) {
      throw new AggregateNotFoundError('User', userId_id.value);
    }

    const friend = await this.userRepository.findById(friendUserId_id);
    if (!friend) {
      throw new AggregateNotFoundError('User', friendUserId_id.value);
    }

    // Remove friendship from both users
    user.removeFriend(friendUserId_id);
    friend.removeFriend(userId_id);

    await this.userRepository.save(user);
    return this.userRepository.save(friend);
  }
}

module.exports = UserDomainService;
