stages:
  - install
  - lint
  - test

install_frontend:
  stage: install
  image: node:18
  script:
    - cd frontend
    - npm install
  cache:
    paths:
      - frontend/node_modules/

install_backend:
  stage: install
  image: node:18
  script:
    - cd backend
    - npm install
  cache:
    paths:
      - backend/node_modules/

lint_frontend:
  stage: lint
  image: node:18
  script:
    - cd frontend
    - npm run lint
    
lint_backend:
  stage: lint
  image: node:18
  script:
    - cd backend
    - npm run lint

test_frontend:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm test

test_backend:
  stage: test
  image: node:18
  script:
    - cd backend
    - npm test